"90% of Inspiration is Perspiration",
"A baby is an alimentary canal with a loud voice at one end and no responsibility at the other",
"A bad custom is like a good cake, better broken than kept",
"A bad excuse is better than none",
"A bad penny always turns up",
"A bad workperson blames their tools",
"A barking dog never bites",
"A best friend is like a four leaf clover, Hard to find and lucky to have",
"A bird can sing with a broken wing, but you cant pluck feathers off a frog",
"A bird in the hand is worth two in the bush",
"A black plum is as sweet as a white",
"A book holds a house of gold",
"A book is like a garden carried in the pocket",
"A bus is a vehicle that runs twice as fast when you are after it as when you are in it",
"A calm sea does not make a skilled sailor",
"A camel is a horse designed by a committee",
"A cat has nine lives",
"A cat may look at a king",
"A cat may look at a Queen",
"A chain is no stronger than its weakest link",
"A change is as good as a rest",
"A cold bitter Christmas, a fat churchyard",
"A constant guest is never welcome",
"A creaking door hangs longest",
"A crowd is not company",
"A danger foreseen is half avoided",
"A day of sorrow is longer than a month of joy",
"A dog who attends a flea circus most likely will steal the whole show",
"A drop of ink may make a million think",
"A drowning person will clutch at straws",
"A fair exchange is no robbery",
"A faithful friend is a medicine for life",
"A fly will not get into a closed mouth",
"A fool and their money are soon parted",
"A fool at forty is a fool indeed",
"A fool finds no pleasure in understanding but delights in airing their own opinions",
"A fool gives; a wise person takes",
"A Fool May Give a Wise person Counsel",
"A fool will laugh when he is drowning",
"A friend in need is a friend indeed",
"A friend is not so soon gotten as lost",
"A friend to all is a friend to none",
"A gentle heart is tied with an easy thread",
"A gentleperson without an estate is a pudding without suet",
"A gift given in secret soothes anger, and a bribe concealed in the cloak pacifies great wrath",
"A golden key opens all doors",
"A good beginning makes a good ending",
"A good conscience is the best divinity",
"A good denial, the best point in law",
"A good lawyer must be a great liar",
"A good person is hard to find",
"A good mate is the road map for the spaghetti junction of life",
"A good name is better than a good face",
"A good name is more desirable than great riches; to be esteemed is better than silver or gold",
"A good tree brings forth good fruit",
"A gossip betrays a confidence, but a trustworthy person keeps a secret",
"A gossips mouth is the devils postbag",
"A guilty conscience needs no accuser",
"A handful of patience is worth more than a bushel of brains",
"A happy heart is better than a full purse",
"A happy heart makes the face cheerful, but heartache crushes the spirit",
"A heart at peace gives life to the body, but envy rots the bones",
"A heavy purse gives to a light heart",
"A hedge between keeps friendship green",
"A helping hand is no farther than at the end of your sleeve",
"A house is not a home",
"A huge part of real love is constant forgiveness",
"A journey of a thousand miles begins with a single step",
"A lender nor borrower be",
"A leopard cannot change its spots",
"A little of what you fancy does you good",
"A long way to go",
"A person in love is a fool, and an old person in love is the greatest fool of all",
"A person is at their tallest when he stoops to help a child",
"A person is judged by their deeds, not by their words",
"A person is known by the company they keep",
"A person that breaks their word bids other be false to him",
"A new broom sweeps clean",
"A new broom sweeps clean, but the old brush knows all the corners",
"A penny always turns up",
"A person who can smile when things go wrong has found someone to blame it on",
"A picture paints a thousand words",
"A positive pessimist is better than a negative optimist",
"A problem is a chance for you to do your best",
"A problem shared is a problem halved",
"A proverb is a true word",
"A proverb never lies, it is only its meaning which deceives",
"A quarrelsome wife is like a constant dripping on a rainy day",
"A reed before the wind lives on, while might oaks do fall",
"A rolling stone gathers no moss",
"A ruler who oppresses the poor is like a driving rain that leaves no crops",
"A scalded cat fears cold water",
"A shining example",
"A short absence quickens love, a long absence kills it",
"A slap on the back is only a few inches away from a kick in the butt",
"A sly rabbit will have three openings to its den",
"A soft answer turneth away wrath",
"A sprat to catch a mackerel",
"A spy with flatulence will always blow their cover",
"A squirrel is just a rat with good PR",
"A stitch in time saves nine",
"A watched pot never boils",
"A wise head keeps a still tongue",
"A wonder lasts but nine days",
"A worry shared is a worry halved",
"Absence makes the heart grow fonder",
"Abundance, like want, ruins many",
"Accidents happen",
"Actions speak louder than words",
"Adversity doesnt build character, it reveals it",
"After a famine in the stall comes a famine in the hall",
"After all is said and done, more is said than done",
"After dark all cats are leopards",
"After dinner rest a while, after supper walk a mile",
"After the game, the king and the pawn go into the same box",
"After the storm comes the calm",
"Age before beauty",
"Age has no friend but the wrinkles of the mind",
"Age is a very high price to pay for maturity",
"Agree, For The Law is Costly",
"All are not cooks that walk with long knives",
"All good things come to he who waits",
"All good things must come to an end",
"All is for the best in the best of the possible worlds",
"All lay loads on a willing horse!",
"All roads lead to Rome",
"All sunshine makes a desert",
"All that glisters is not gold",
"All the world loves a lover",
"All things come to those who wait",
"All work and no play makes Jack a dull boy",
"All you need is love",
"An ant may well destroy a whole dam",
"An English Summer, Three Hot Days and a Thunderstorm",
"An eye for an eye, a tooth for a tooth",
"An old fox is not easily snared",
"An old Ox makes a straight furrow",
"An ounce of practice is worth a pound of precept",
"Another day, another dollar",
"Any fool can criticise, condemn and complain and most fools do",
"Any port in a storm",
"Anybody can make theirtory Only a great person can write it",
"Appearances are deceptive",
"April is the cruellest month",
"Art has no enemy but ignorance",
"Artificial intelligence is no match for natural stupidity",
"Ask a silly question and you get a silly answer",
"Ask no questions and hear no lies",
"At the end of the game, the King and the pawn go back in the same box",
"Bad news travels fast",
"Barking dogs seldom bite",
"Be a good sport - wherever you go",
"Be first at the feast, and last at the fight",
"Be just before you are generous",
"Be kind to people on the way up, you may need them when you are on your way down",
"Beauty is in the eye of the beholder",
"Beauty is only skin deep",
"Beauty without virtue is a flower without perfume",
"Bees that have honey in their mouths have stings in their tails",
"Beggars and borrowers cannot be choosers",
"Believe nothing of what you hear, and only half of what you see",
"Better a dry crust with peace and quiet than a house full of feasting, with strife",
"Better a meal of vegetables where there is love than a fattened calf with hatred",
"Better an open enemy, than a false friend",
"Better bend than break",
"Better die with honor than live with shame",
"Better do it than wish it done",
"Better late than never",
"Better one house spoiled than two",
"Better safe than sorry",
"Better to aim high and miss, than to aim low and reach target!",
"Better to be alone than in bad company",
"Better to be envied than pitied",
"Better to be lowly in spirit and among the oppressed than to share plunder with the proud",
"Better to be safe than sorry",
"Better to have loved and lost, than never have loved at all",
"Better to light a candle than to curse the darkness",
"Better to live on a corner of the roof than share a house with a quarrelsome wife",
"Better to meet a bear robbed of her cubs than a fool in their folly",
"Better to remain silent and appear a fool, than to open your mouth and remove all doubt",
"Better wed over the mixen than over the moor",
"Birds of a feather flock together",
"Bitter pills may have blessed effects",
"Blood is thicker than water",
"Books and friends should be few and good",
"Catch not at the shadow and lose the substance",
"Charity begins at home",
"Charity covers a multitude of sins",
"Cheats never prosper",
"Children should be seen and not heard",
"Civility costs nothing",
"Cold hands, warm heart",
"Common fame is seldom to blame",
"Confession is good for the soul",
"Confidence is a plant of slow growth",
"Constant dripping wears away the stone",
"Cultivate money and you grow rich, Cultivate mind and you raise culture",
"Curiosity killed the cat",
"Curses, like chickens, come home to roost",
"Cut your coat according to your cloth",
"Danger can never be overcome without taking risks",
"Dead men tell no tales",
"Death is the great leveller",
"Death pays all debts",
"Diamonds cut diamonds",
"Different strokes for different folk",
"Diligence is the mother of good fortune",
"Discretion is the better part of valour",
"Distance lends enchantment to the view",
"Distance makes the heart grow fonder",
"Do as I say, and not as I do",
"Do as you would be done by",
"Do not look where you fell, but where you slipped",
"Do not search for a calf under an ox",
"Do not use a hatchet to remove a fly from a friends forehead",
"Do not wear out your welcome",
"Do right and fear no person",
"Do unto others as you would like them to do unto you",
"Don,t count the days, make the days count!",
"Don't make love at the garden gate, love is blind but the neighbours aint",
"Doubt is the beginning not the end of wisdom",
"Due to the presence of fools, wise people stand out",
"Early to bed and early to rise, make a person healthy, wealthy and wise",
"Eat well, stay fit, die anyway",
"Empty sacks will never stand upright",
"Enough is as good as a feast",
"Even a clock that does not work is right twice a day",
"Even in laughter the heart may ache, and joy may end in grief",
"Every bird loves to hear himself sing",
"Every cloud has a silver lining",
"Every dog has their day",
"Every family has a skeleton in the cupboard",
"Every flow hath its ebb",
"Every person has their price",
"Every picture tells a story",
"Every step of life is a risk",
"Everyday is a fresh slate",
"Everyone stretches their legs according to the length of their coverlet",
"Everything must have a beginning",
"Excess of ceremony shows want of breeding",
"Experience is a great servant",
"Experience is a wonderful thing It enables you to recognise a mistake when you make it again",
"Experience is better bought than taught",
"Experience is the best teacher",
"Facts are stubborn things",
"Fair exchange is no robbery",
"Fair without , false within",
"Faith will move mountains",
"Fall seven times, stand up eight",
"Familiarity breeds contempt",
"Fate leads the willing but drives the stubborn",
"Fear lends wings",
"Feed a cold starve a fever",
"Fight fire with fire",
"Fight truth decay, read the bible",
"Finders keepers, losers weepers",
"Fine feathers make fine birds",
"Fine words butter no parsnips",
"Fish and guests smell in three days",
"Fish are no respectors of humann boredom, so why go angling",
"Flies come to feasts unasked",
"Flies never visit an egg that has no crack",
"Fogiveness is the fragrance the violet sheds on the foot that crushed it",
"Folly grows without watering",
"Forbidden fruits create many jams",
"Forewarned is forearmed",
"Forgive and forget",
"Fortune favours the brave",
"Friends are made by many acts - and lost by only one",
"Friendship is like money, easier made than kept",
"From clogs to clogs in only three generations",
"From the sweetest wine the tartest vinegar",
"Fruit out of season, sorrow out of reason",
"Gentle is that gentle does",
"Give a clown a finger and he will take your hand",
"Gluttony kills more than the sword",
"Go to heaven for the climate and hell for the company",
"Golden dishes will never turn black",
"Good and quickly seldom meet",
"Good broth may be made in an old pot",
"Good fences make good neighbours!",
"Good friends are hard to find, harder to leave, and impossible to forget",
"Good people are scarce",
"Good talk saves the food",
"Goodness is better than beauty",
"Grease is the only cure for a hangover",
"Great minds think alike, simple minds cant think of anything different",
"Great oaks from little acorns grow",
"Greedy folks have long arms",
"Gut No Fish Till You Get Them",
"Half a loaf is better than no bread",
"Happiness is wanting what you have - not having what you want",
"Hard work never did anyone any harm",
"Haste makes waste",
"Hasty climbers have sudden falls",
"Hatred stirs up dissension, but love covers over all wrongs",
"Home is where the heart is",
"Home is where you hang your hat",
"Honesty is the best policy",
"Hunger is the best sauce",
"I pointed out to you the stars and all you saw was the tip of my finger",
"Idle people lack no excuses",
"If anything can go wrong, it will",
"If in doubt, mumble",
"If life deals you lemons make lemonade",
"If the cap fits, wear it",
"If the wind will not serve, take to the oars",
"If there were no lossers there could be no winners",
"If you believe everything you read, you better not read",
"If you get it overnight, you can lose it just as quick",
"If you lie down with dogs you will come up with fleas",
"If you want a place in the sun, you must leave the shade of the family tree",
"If you wish to be loved, love",
"If you would enjoy the fruit, pluck not the flower",
"Ignorance is bliss",
"Ill-gotten gains never prosper",
"Imagination is the highest kite you can fly",
"Imitation is the sincerest form of flattery",
"In a battle between elephants, the ants get squashed",
"In April,a youg persons thoughts turn to fancy!",
"In black and white",
"In for a penny, in for a pound",
"In the coldest flint there is hot fire",
"In the house of the wise are stores of choice food and oil, but a foolish person devours all he has",
"In the land of hope there is never any winter",
"In the Land of the Blind the One Eyed person is King",
"In vino veritas",
"Inverted comma",
"Is better to light a candle than to curse the darkness",
"It is nice to be important but it is more important to be nice",
"It is a long lane that has no turning",
"It is a silly fish that is caught twice with the same bait",
"It is better to love and lost than never to love at all",
"It is better to travel hopefully than to arrive",
"It is better to wear out than to rust out",
"It is easier to get forgiveness than permission",
"It is foolish to deal with a fool",
"It is good to be knowledgeable, but better to be lovable",
"It is good to have company in misery",
"It is in vain to cast your net where there is no fish",
"It is never too late to be what you might have been",
"It is possible to give without loving but it is impossible to love without giving",
"It is what is in the mind when sober, that comes out of the mouth when drunk",
"It never rains but it pours",
"It takes all sorts to make a world",
"It takes one bad apple to spoil the barrel!",
"It takes one day to destroy a house but to build a new one will take months, perhaps years",
"It takes one to know one",
"It takes two to make a quarrel",
"It takes two to tango",
"It will all come out in the wash",
"It will all come right in the wash",
"It's the thought that counts",
"Its a dogs life",
"Its a wise child that knows its own father",
"Its only rock n roll but I like it",
"Its too late to shut the stable door after the horse has bolted",
"Jack of all trades, master of none",
"Judge not that you be not judged",
"Just between you and me",
"Keep your chin up",
"Keep your eyes on the stars, and your feet on the ground",
"Keep your friends close but your enemies closer",
"Keep your powder dry",
"Kill not the goose that lays the golden egg",
"Kill two birds with one stone",
"Kiss and make up",
"Kiss and tell",
"Know which side your bread is buttered",
"Knowing is not enough; We must Apply Willing is not enough; We must Do",
"Laugh and the world laughs with you, cry and you cry alone",
"Laughter is the best medicine",
"Laughter is the closest distance between two people",
"Lazy hands make a person poor, but diligent hands bring wealth",
"Lean liberty is better than fat slavery",
"Lear from the past, Live for today Look for tomorrow, take a nap ttheir afternoon",
"Learn to say no It will be of more use to you than to be able to read Latin",
"Learning is a treasure that will follow its owner everywhere",
"Least said soonest mended",
"Lend your money and lose your friend",
"Let bygones be bygones",
"Let sleeping dogs lie",
"Let the buyer beware",
"Life after death",
"Life begins at forty",
"Life is a mystery to be lived, not a problem to be solved",
"Life is beautiful",
"Life is just a bowl of cherries",
"Life is like a box of chocolates, sometimes hard, sometimes soft",
"Life is like a drawing pin - sharp at one end, and flat at the other",
"Life is like a good book, the more you get into it the more it makes sense",
"Life is like a horse race there are winners and losers",
"Life is not all beer and skittles",
"Life is one long catwalk",
"Lightning never strikes twice",
"Lightning never strikes twice in the same place",
"Like a roaring lion or a charging bear is a wicked person ruling over a helpless people",
"Like clouds and wind without rain is a person who boasts of gifts he does not give",
"Like father, like son",
"Like flogging a dead horse",
"Like music to my ears",
"Like the measles, love is most dangerous when it comes late in life",
"Line up in alphabetical order",
"Listen to advice and accept instruction, and in the end you will be wise",
"Little and large",
"Little Strokes Fell Great Oaks",
"Little things please little minds",
"Little white lie",
"Live and learn",
"Live and let live",
"Live to the point of tears",
"Long time no see",
"Look after number one",
"Look before you leap",
"Look both ways",
"Look good, feel good",
"Look on the bright side",
"Look the other way",
"Lookers on see most of the game",
"Lost in the post",
"Lots of people confuse bad personagement with destiny",
"Love conquers all",
"Love is an ideal thing, marriage a real thing",
"Love is blind",
"Love is like a fire, it can either warm your heart or burn your house down",
"Love is the strangest thing",
"Love laughs at the locksmiths",
"Love makes the world go round",
"Love many, trust few, but always paddle your own canoe",
"Love nature , live lightly",
"Love starts with a smile, grows with a kiss, and ends with a tear",
"Love thy neighbour as thy self",
"Love will find a way",
"Loving life is living life to the fullest",
"Lucky at cards, unlucky in love",
"Make hay while the sun shines",
"Make love not war",
"person cannot live on bread alone",
"person in the moon",
"person who wants pretty nurse, must be patient",
"personners maketh person",
"many a mickle makes a muckle",
"many a true word is spoken in jest",
"many are called but few are chosen",
"many hands make light work",
"many people know how to say nothing; few know when",
"many things are lost for want of asking",
"March comes in like a lion and goes out like a lamb",
"March winds and April showers bring forth May flowers",
"Marry in haste, and repent at leisure",
"Melt the icy fingers of fear with the sunshine of hope",
"Men are from earth Women are from earth Deal with it",
"Merry Nights Make Sorry Days",
"Middle age is when broadness of the mind and narrowness of the waist change places",
"Might is right",
"Mind your own business",
"Mini-skirt",
"Misery loves company",
"Money is the root of all evil",
"Money makes the world go around",
"More haste less speed",
"Mother knows best",
"Motivation is what gets you started habit is what keeps you going",
"Much too much",
"Murder will out",
"Necessity is the mother of invention",
"Needs must when the devil drives",
"Never be afraid to sit awhile and think",
"Never choose bedlinen or a wife by candlelight",
"Never eat an oyster unless there is an R in the month",
"Never go to bed on an argument",
"Never judge a book by its cover",
"Never judge by appearences",
"Never judge someone until you have travelled a mile in their shoes",
"Never look a gift horse in the mouth",
"Never make a mountain out of a molehill - The mountain will arrive soon enough",
"Never murder a person who is committing suicide",
"Never play leapfrog with a unicorn",
"Never put off til tomorrow what you can do today",
"Never put your tongue on an iceberg",
"Never say die",
"Never speak ill of the dead",
"Never stand on the tail of a hedgehog after midnight",
"Never the twain shall meet",
"Never too old to learn",
"Never trouble trouble till trouble troubles you",
"Night is the Mother of Counsel",
"No Good Building Without a Good Foundation",
"No great genius has ever existed without some touch of madness",
"No person is a hero to their valet",
"No person is an island",
"No person is wise at all times",
"No matter how long a log stays in the water it does not become a crocodile",
"No news is good news",
"No one grows old by living; only by losing interest in living",
"No one is expected to achieve the impossible",
"No pain, no gain",
"No wind, no waves",
"None but the brave deserve the fair",
"None but the wearer knows where the shoe pinches",
"None so deaf as those who will not hear",
"Not to know is bad; not to wish to know is worse",
"Nothing is certain but death and taxes",
"Nothing is interesting if you are not interested",
"Nothing seems expensive on credit",
"Nothing succeeds like success",
"Nothing that is worth knowing can be taught",
"Nothing to worry about",
"Nothing ventured, nothing gained",
"Nowt so queer as folk!",
"Old fish and young flesh feed men best",
"Old friends and wine are best",
"Old habits die hard",
"Old sins cast long shadows",
"On cloud nine",
"On second thoughts",
"On the crest of a wave",
"On the Turf all men are equal, and under it",
"Once a word leaves your mouth, you cannot chase it back even with the swiftest horse",
"Once bitten twice shy",
"Once in a blue moon",
"Once in a while, right in the middle of an ordinary life, love gives us a fairy tale",
"Once seen never forgotten",
"One beats the bush, another takes the bird",
"One cannot quarrel without an opponent",
"One foolish sheep will lead the flock",
"One for sorrow, two for joy, three for a girl, four for a boy, five for silver, six for gold seven for a secret not to be sold Eight for heaven nine for hell and ten for the devils own cell",
"One good turn deserves another",
"One good turn deserves half the blankets",
"One in a million",
"One persons loss is another persons gain",
"One persons meat is another persons poison!",
"One of these days is none of these days",
"One thing after another",
"One volunteer is worth ten pressed men",
"One who has the reputation of an early riser may safely lie in bed until noon",
"One years seeding means seven years weeding",
"Only fools and horses work",
"Only mad dogs and englishmen go out in the midday sun",
"Only time will tell",
"Only when all contribute their firewood can they build up a strong fire",
"Opportunities always look bigger going than coming",
"Opportunity makes a thief",
"Opportunity seldom knocks twice",
"Out of sight, out of mind",
"Out of the blue",
"Out of the mouths of babes and sucklings",
"Over the moon",
"Pain in the neck",
"Pain is so close to pleasure",
"Pain is temporary, victory is forever",
"Pardon all but theyself",
"Past cure, past care",
"Patience is a virtue",
"Patience is bitter, but it bears sweet fruit",
"Penny wise, pound foolish",
"People who think the world revolves around them have no sense of direction",
"Perfection is inperfect",
"Pick your friends like you pick your fruit",
"Plant the crab tree where you will, it will never bear pippins",
"Play with fire",
"Poor men seek meat for their stomach; rich men stomach for their meat",
"Possessions dwindle; I mourn their loss But I mourn the loss of time much more, for anyone can save their purse, but none can win back lost time",
"Possessions dwindle; I mourn their loss But I mourn the loss of time much more, for anyone can save their purse, but none can win back lost time",
"Practice makes perfect",
"Practice what you preach",
"Pretty as a picture",
"Prevention is better than cure",
"Pride comes before a fall",
"Procrastination is the thief of time",
"Promises are like babies Easy to make, hard to deliver",
"Put the cat out",
"Quality is an excuse for lack of quantity",
"Quality is better than quantity",
"Quickly come, quickly go",
"Rain before seven, fine before eleven",
"Rain, Rain, go away, come back another day",
"Rained on ground hardens (Japanese Proverb)",
"Rats desert a sinking ship",
"Reading between the lines",
"Red in the face",
"Red sky at night",
"Red sky at night shepherds delight,red sky in the morning,shepherds warning",
"Red, white and blue",
"Revenge is a dish best served cold",
"Revenge is sweet",
"Right between the eyes",
"Righteousness exalts a nation but sin is a disgrace to any people",
"Robbing Peter to pay Paul",
"Saying is one thing; doing another",
"Second place is first loser",
"See Naples and die",
"Seeing is believing",
"Seldom seen, soon forgotten",
"Seven-fifths of all people do not understand fractions",
"Sex takes up the least amount of time and causes the most amount of trouble",
"Share and share alike!",
"Shopping is a therapy",
"Shut up and sit down",
"Sign on the dotted line",
"Silence is golden",
"Silence is the fence around wisdom",
"Sinking ship",
"Size matters",
"Sleep is better than medicine",
"Small talk",
"Small time crook",
"Smile and the world smiles with you, snore and you sleep alone",
"Smooth runs the water where the brook is deep",
"Smooth seas do not make skillful sailors",
"So long as you do your best in life, whatever happens will be for the best",
"Softly, softly, catchee monkey",
"Some are Wise and Some are Otherwise",
"Some are wise and some are otherwise",
"Sometimes the majority only means all the fools are on the same side",
"Spare the rod and spoil the child",
"Speak when you are spoken to",
"Split second timing",
"Spots before the eyes",
"St Swithins Day, if thou does rain, for forty days it will remain, St Swithins day if thou be fair for forty days twill rain no more",
"Star turn",
"Sticks and stones may break my bones but names will never hurt me",
"Still waters run deep",
"Stir With a Knife, Stir Up Strife",
"Stone is heavy and sand a burden, but provocation by a fool is heavier than both",
"Strangers are just friends you have not met yet",
"Strike while the iron is hot",
"Success has many fathers, while failure is an orphan",
"Sugar cube",
"Sunlight penetrates even the thinnest crack",
"Sweetheart",
"Swim in the sea",
"Sympathy without relief is like mustard without beef",
"Tailors and writers must mind the fashion",
"Take a hair of the dog that bit you",
"Take care of the pennies and the pounds will take care of themselves",
"Take heed of reconciled enemies and of meat twice boiled",
"Take your time and time will take you",
"Talk about things of tomorrow and the mice inside the ceiling laugh",
"Talk is cheap",
"Teachers open the door, but you must enter by yourself",
"Teaching of others teacheth the teacher",
"The Absent are Always Wrong",
"The Ass Loaded With Gold Still Eats Ttheirtles",
"The best advice is found on the pillow",
"The best doctors are Dr Diet, Dr Quiet and Dr Merryperson",
"The Best Fish Swim Near the Bottom",
"The best is yet to come",
"The best of men are but men at best",
"The best things come in small packages",
"The best things in life are free",
"The best throw of the dice is to throw them away",
"The Best Wine Comes Out of an Old Vessel",
"The bigger they are, the harder they fall",
"The birds and the bees",
"The cobra will bite you whether you call it cobra or Mr Cobra",
"The company makes the feast",
"The country is in ruins, and there are still mountains and rivers - japanese proverb",
"The course of true love never did run smooth",
"The darkest hour is just before dawn",
"The devil find work for idle hands to do",
"The Devil goes shares in gaming",
"The Devil rides upon a fiddlestick",
"The devil tempts all, but the idle person tempts the devil",
"The difficult we do at once, the impossible takes a little longer",
"The early bird catches the worm",
"The early bird may get the worm, but the second mouse gets the cheese",
"The early worm enjoys a leisurely breakfast",
"The end justifies the means",
"The eyes are the window of the soul",
"The eyes speak as much as the mouth",
"The faintest ink is more powerful than the strongest memory",
"The Fairest Rose at Last is Withered",
"The Family That Prays Together Stays Together",
"The female of the species is more deadly than the male",
"The first faults are theirs that commit them, the second theirs that permit them",
"The first step is the hardest",
"The fish will soon be caught, that nibbles at every bait",
"The fruit does not fall far from the tree.",
"The Gods Send Nuts to those who have no Teeth",
"The grass is always greener on the other side of the fence",
"The hand that rocks the cradle rules the world",
"The higher the monkey climbs, the more he shows their tail",
"The higher the tree, the sweeter the plum",
"The higher you climb up the ladder, the more people can see your arse",
"The horses of hope gallop, but the asses of experience go slowly",
"The King can make a knight, but not a gentleperson",
"The last drop makes the cup run over",
"The longest day must have an end",
"The longest rope has an end",
"The person who removes a mountain begins by carrying away small stones",
"The Moon does not heed the barking of dogs",
"The more one knows, the less one believes",
"The more the merrier",
"The more you get, the more you want",
"The nearer the bone the sweeter the meat",
"The nearer to the church, the farther from God",
"The old believe everything, the middle aged suspect everything, the young know everything",
"The One who tells the stories rules the world",
"The pen is mightier than the sword",
"The pot calls the kettle black",
"The price of greatness is responsibility",
"The price of liberty is eternal vigilance",
"The proof of the pudding is in the eating",
"The righteous person leads a blameless life; blessed are their children after him",
"The road to hell is paved with good intentions",
"The rotten apple injures its neighbours",
"The spirit is willing but the flesh is weak",
"The stick is the surest peacemaker",
"The tide never goes out so far but it always comes in again",
"The tongue ever turns to the aching tooth",
"The tongue that brings healing is a tree of life, but a deceitful tongue crushes the spirit",
"The trouble with experience is that by the time you have it, you are too old to take advantage of it",
"The truth will out",
"The West Wind Always Brings Wet Weather, The East Wind Wet and Cold Together, the South Wind Surely Brings Us Rain, the North Wind Blows It Back Again",
"The world is full of willing people: some willing to work and some willing to let them",
"The young person thinks the old persons stupid but the old person KNOWS the young person is",
"There are always ears on the other side of the wall",
"There Are No Atheists in Foxholes",
"There are none so blind as those that will not see",
"There are two sides to every question",
"There but for the grace of God go I",
"There is a skeleton in every cupboard",
"There is a time and a place for everything",
"There is a time to speak and a time to be silent",
"There is always some madness in love But there is also always some reason in madness",
"There is always somebody worst of then yourself no matter how bad things seem",
"There is an exception to every rule",
"There is more than one way to skin a cat",
"There is no accounting for taste",
"There is no difference between a wise person and a fool when they fall in love",
"There is no jollity but hath a smack of folly",
"There is no physician like a true friend",
"There is no such thing as a free lunch",
"There is no time like the present",
"There is safety in numbers",
"There will be rubs in the smoothest road",
"They Brag Most That Can Do the Least",
"They that dance must pay the fiddler",
"They that walk much in the sun will be tanned at last",
"Things can only get better",
"Things that come to those who wait may be things left by those who got there first",
"Think before you speak",
"Think Much, Speak Little and Write Less",
"Third time lucky",
"Those who cast the votes decide nothing Those who count the votes decide everything",
"Those who play the game do not see it as clearly as those who watch",
"Though the wound be healed, a scar remains",
"Three wise men",
"Time and tide wait for no person",
"Time is a great healer",
"Time to spare",
"Time waits for nobody",
"Tis better to get things for free, than to work up a sweat",
"To deceive oneself is very easy",
"To err is human, to forgive divine",
"To handle yourself, use your head; to handle others, use your heart",
"To have is to hold and to hold is to have",
"To know the road ahead, ask those coming back",
"To many people in a dustbin means there not much room in side",
"To say that a person cannot love one woperson at a time is ridiculous It is like saying a musician needs more than one violin to play the same piece of music",
"To the jaundiced eye all things look yellow",
"To the victor the spoils",
"To the world you may be one person but to one person you may be the world",
"To thine own self be true",
"Tomorrow never comes",
"Too funny for words",
"Too many chiefs and not enough indians",
"Too many clicks spoil the browse",
"Too many cooks spoil the broth",
"Train a child in the way he should go, and when he is old he will not turn from it",
"True blue will never stain",
"True love is like a teardrop in Niagra falls",
"True love never grows old",
"Trust is the mother of deceit",
"Turn the other cheek",
"Two Dogs Fight for a Bone, and a Third Runs Away With it",
"Two fools in a house are too many",
"Two heads are better than one",
"Two wrongs do not make a right",
"Two wrongs may not make a right but three rights make a left",
"Under the thorn grow the roses",
"United we stand, divided we fall",
"Use it or lose it",
"Use soft words and hard arguments",
"Variety is the spice of life",
"Virtue is its own reward",
"Virtues all agree, but vices fight one another",
"Visit your aunt, but not every day of the year",

"Walk before you can run",
"Walls have ears",

